export const CONTACT = {
  phone: '(443) 547-1326',
  phoneRaw: '+14435471326',
  whatsappRaw: '14435471326',
  email: 'trendycheff@gmail.com',
  chef: 'Trendy Cheff',
  location: 'Maryland',
};

export const CATEGORIES = [
  { id: 'indo_chinese', label: 'Indo-Chinese' },
  { id: 'main_course_non_veg', label: 'Main Course (Non-Veg)' },
  { id: 'main_course_veg', label: 'Main Course (Veg)' },
  { id: 'rice', label: 'Rice' },
  { id: 'biryani_flavors', label: 'Biryani Flavors' },
  { id: 'salad', label: 'Salad' },
  { id: 'italian', label: 'Italian' },
  { id: 'appetizers_veg', label: 'Appetizers (Veg)' },
  { id: 'appetizers_non_veg', label: 'Appetizers (Non-Veg)' },
  { id: 'tandoori_treasures', label: 'Tandoori Treasures' },
  { id: 'chefs_specials', label: "Chef's Specials" },
];

export const DELIVERY_FEE = 25;
export const SMALL_TRAY_MULTIPLIER = 0.65;

export const PAYMENT_METHODS = [
  { id: 'square_card', label: 'Pay with card' },
  { id: 'paypal', label: 'PayPal' },
  { id: 'venmo', label: 'Venmo' },
  { id: 'cashapp', label: 'Cash App' },
];

export const SAMPLE_MENU = [
  // ── Appetizers (Veg) ────────────────────────────────────────────
  {
    id: 'av1',
    name: 'Tikki Cholley',
    description: 'Crispy potato tikki served with choley.',
    category: 'appetizers_veg',
    price_medium: 75,
    price_large: 130,
    price_per_piece: null,
    medium_label: 'Medium Tray',
    large_label: 'Large Tray',
    image_url:
      'https://lh3.googleusercontent.com/d/1j4FWEjPe-_fnDaDT2XsBEPv5jDk3BFm_=w800',
    is_available: true,
    sort_order: 1,
  },
  {
    id: 'av2',
    name: 'Samosa Cholley',
    description: 'Crispy samosas with spiced choley.',
    category: 'appetizers_veg',
    price_medium: 75,
    price_large: 130,
    price_per_piece: null,
    medium_label: 'Medium Tray',
    large_label: 'Large Tray',
    image_url:
      'https://lh3.googleusercontent.com/d/1lipGESxkYjnRXY7-0NZ8OjE3FqJ1BDM5=w800',
    is_available: true,
    sort_order: 2,
  },
  {
    id: 'av3',
    name: 'Alu Ki Sabzi / Kachori',
    description: 'Fluffy kachori with spiced potato curry.',
    category: 'appetizers_veg',
    price_medium: 75,
    price_large: 130,
    price_per_piece: null,
    medium_label: 'Medium Tray',
    large_label: 'Large Tray',
    image_url:
      'https://lh3.googleusercontent.com/d/1ZLhaCxiqhVxU73gUszsDTP5-piU-KysM=w800',
    is_available: true,
    sort_order: 3,
  },
  {
    id: 'av4',
    name: 'Veg Puff Patties',
    description: 'Flaky pastry stuffed with spiced vegetables. Sold per piece.',
    category: 'appetizers_veg',
    price_medium: null,
    price_large: null,
    price_per_piece: 4,
    medium_label: null,
    large_label: null,
    image_url:
      'https://lh3.googleusercontent.com/d/1L9BWMuQWBGxy7BvNz6QmBUsvqZIwMmyp=w800',
    is_available: true,
    sort_order: 4,
  },

  // ── Appetizers (Non-Veg) ────────────────────────────────────────
  {
    id: 'anv1',
    name: 'Chicken Salami Cold',
    description: 'Chilled chicken salami slices, perfect starter platter.',
    category: 'appetizers_non_veg',
    price_medium: 120,
    price_large: 210,
    price_per_piece: null,
    medium_label: 'Medium Tray',
    large_label: 'Large Tray',
    image_url:
      'https://lh3.googleusercontent.com/d/1Vvv4OmgPf3d9ZeM5m_v_ecdgxNJoPsj5=w800',
    is_available: true,
    sort_order: 1,
  },
  {
    id: 'anv2',
    name: 'Chicken Tikka',
    description: 'Yogurt-marinated chargrilled chicken skewers.',
    category: 'appetizers_non_veg',
    price_medium: 110,
    price_large: 190,
    price_per_piece: null,
    medium_label: 'Medium Tray',
    large_label: 'Large Tray',
    image_url:
      'https://lh3.googleusercontent.com/d/1kFBePvHd5WpkGAbe79aecwWDPvKpdi1U=w800',
    is_available: true,
    sort_order: 2,
  },
  {
    id: 'anv3',
    name: 'Lehsuni Tikka',
    description: 'Garlic-loaded juicy chicken tikka.',
    category: 'appetizers_non_veg',
    price_medium: 110,
    price_large: 190,
    price_per_piece: null,
    medium_label: 'Medium Tray',
    large_label: 'Large Tray',
    image_url:
      'https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=800',
    is_available: true,
    sort_order: 3,
  },
  {
    id: 'anv4',
    name: 'Chicken Malai Tikka',
    description: 'Creamy mild chicken tikka with malai marinade.',
    category: 'appetizers_non_veg',
    price_medium: 110,
    price_large: 190,
    price_per_piece: null,
    medium_label: 'Medium Tray',
    large_label: 'Large Tray',
    image_url:
      'https://lh3.googleusercontent.com/d/14qg_aJoA5dohm1qeaAyyXDIg-jSgXK7h=w800',
    is_available: true,
    sort_order: 4,
  },
  {
    id: 'anv5',
    name: 'Chicken Tandoori (WB)',
    description: 'Whole-bird West Bengal-style tandoori chicken.',
    category: 'appetizers_non_veg',
    price_medium: 120,
    price_large: 210,
    price_per_piece: null,
    medium_label: 'Medium Tray',
    large_label: 'Large Tray',
    image_url:
      'https://lh3.googleusercontent.com/d/1rNA60w0dGDiM6CkRre2hPTc3yhaLXokj=w800',
    is_available: true,
    sort_order: 5,
  },

  // ── Main Course (Veg) ───────────────────────────────────────────
  {
    id: 'mv1',
    name: 'Dal Makhani',
    description: 'Black lentils slow-simmered overnight with cream and butter.',
    category: 'main_course_veg',
    price_medium: 105,
    price_large: 160,
    price_per_piece: null,
    medium_label: 'Medium Tray',
    large_label: 'Large Tray',
    image_url:
      'https://lh3.googleusercontent.com/d/1xwsZ1ZQ_nsF_zgo2v6rrvQMPBckX8uVM=w800',
    is_available: true,
    sort_order: 1,
  },
  {
    id: 'mv2',
    name: 'Yellow Dal Tadka',
    description: 'Yellow lentils tempered with ghee, cumin and garlic.',
    category: 'main_course_veg',
    price_medium: 105,
    price_large: 160,
    price_per_piece: null,
    medium_label: 'Medium Tray',
    large_label: 'Large Tray',
    image_url:
      'https://lh3.googleusercontent.com/d/1msXJ7-6qxDMbu_3H-0HVH7XCpZTsvoMK=w800',
    is_available: true,
    sort_order: 2,
  },
  {
    id: 'mv3',
    name: 'Rajma Curry / Rajma Masala',
    description: 'Kidney beans in thick tomato-onion gravy.',
    category: 'main_course_veg',
    price_medium: 105,
    price_large: 160,
    price_per_piece: null,
    medium_label: 'Medium Tray',
    large_label: 'Large Tray',
    image_url:
      'https://lh3.googleusercontent.com/d/1gVBR49PcpWVG2RbuCgNypTZMcvqFx--v=w800',
    is_available: true,
    sort_order: 3,
  },
  {
    id: 'mv4',
    name: 'Chana Masala',
    description: 'Spiced chickpeas in classic North-Indian masala.',
    category: 'main_course_veg',
    price_medium: 105,
    price_large: 160,
    price_per_piece: null,
    medium_label: 'Medium Tray',
    large_label: 'Large Tray',
    image_url:
      'https://lh3.googleusercontent.com/d/1JJbu03EJehyBxlLfXdDo1X5T1HDVI1SL=w800',
    is_available: true,
    sort_order: 4,
  },
  {
    id: 'mv5',
    name: 'Pindi Chana',
    description: 'Smoky dry-style chickpeas from Punjab.',
    category: 'main_course_veg',
    price_medium: 105,
    price_large: 160,
    price_per_piece: null,
    medium_label: 'Medium Tray',
    large_label: 'Large Tray',
    image_url:
      'https://lh3.googleusercontent.com/d/1seweq_dZzPuxeugCKnC0pXY9EU_l418l=w800',
    is_available: true,
    sort_order: 5,
  },
  {
    id: 'mv6',
    name: 'Jeera Aloo / Jeera Aaloo',
    description: 'Cumin-tempered potatoes, dry and crisp.',
    category: 'main_course_veg',
    price_medium: 105,
    price_large: 160,
    price_per_piece: null,
    medium_label: 'Medium Tray',
    large_label: 'Large Tray',
    image_url:
      'https://lh3.googleusercontent.com/d/1woDWSqlUK2btuRuzair0obeBh7-UhMSJ=w800',
    is_available: true,
    sort_order: 6,
  },
  {
    id: 'mv7',
    name: 'Aaloo Gobi',
    description: 'Potato and cauliflower with turmeric and ginger.',
    category: 'main_course_veg',
    price_medium: null,
    price_large: null,
    price_per_piece: null,
    medium_label: 'Medium Tray',
    large_label: 'Large Tray',
    image_url:
      'https://lh3.googleusercontent.com/d/1SyyDQbL8x-AP3ntT1q9BF76p-TSy4Uqq=w800',
    is_available: true,
    sort_order: 7,
  },
  {
    id: 'mv8',
    name: 'Baingan Bharta',
    description: 'Smoky mashed roasted eggplant with spices.',
    category: 'main_course_veg',
    price_medium: 105,
    price_large: 160,
    price_per_piece: null,
    medium_label: 'Medium Tray',
    large_label: 'Large Tray',
    image_url:
      'https://lh3.googleusercontent.com/d/1MPOdSYSC7rRkucyB1MTeBfnrXJ-6zGLv=w800',
    is_available: true,
    sort_order: 8,
  },
  {
    id: 'mv9',
    name: 'Palak Paneer',
    description: 'Paneer cubes in silky spinach gravy.',
    category: 'main_course_veg',
    price_medium: 110,
    price_large: 170,
    price_per_piece: null,
    medium_label: 'Medium Tray',
    large_label: 'Large Tray',
    image_url:
      'https://lh3.googleusercontent.com/d/1_QN6uAaTbdoJ251riBR1x90p_rQohZbV=w800',
    is_available: true,
    sort_order: 9,
  },
  {
    id: 'mv10',
    name: 'Shahi Paneer',
    description: 'Rich royal-style paneer in creamy cashew-tomato gravy.',
    category: 'main_course_veg',
    price_medium: 110,
    price_large: 170,
    price_per_piece: null,
    medium_label: 'Medium Tray',
    large_label: 'Large Tray',
    image_url:
      'https://lh3.googleusercontent.com/d/1O17X3tuUgz2aBX2qjXt5N63MZi4EYNMI=w800',
    is_available: true,
    sort_order: 10,
  },
  {
    id: 'mv11',
    name: 'Kadhai Paneer',
    description: 'Paneer and peppers in smoky kadhai masala.',
    category: 'main_course_veg',
    price_medium: 110,
    price_large: 170,
    price_per_piece: null,
    medium_label: 'Medium Tray',
    large_label: 'Large Tray',
    image_url:
      'https://lh3.googleusercontent.com/d/12BpQ3UVDnc41YIFHY2tcIK8c-Zu37XZQ=w800',
    is_available: true,
    sort_order: 11,
  },
  {
    id: 'mv12',
    name: 'Paneer Korma',
    description: 'Mild creamy paneer curry with nuts.',
    category: 'main_course_veg',
    price_medium: 110,
    price_large: 170,
    price_per_piece: null,
    medium_label: 'Medium Tray',
    large_label: 'Large Tray',
    image_url:
      'https://lh3.googleusercontent.com/d/1IUvrYa__PyM5TBUzPgdDgNiZ-G59tpbx=w800',
    is_available: true,
    sort_order: 12,
  },
  {
    id: 'mv13',
    name: 'Mutter Paneer / Mattar Paneer',
    description: 'Paneer and peas in tomato-cashew gravy.',
    category: 'main_course_veg',
    price_medium: 110,
    price_large: 170,
    price_per_piece: null,
    medium_label: 'Medium Tray',
    large_label: 'Large Tray',
    image_url:
      'https://lh3.googleusercontent.com/d/12IXOk6uV-KyQ5tLOYx6nVaKN0jKQJywf=w800',
    is_available: true,
    sort_order: 13,
  },
  {
    id: 'mv14',
    name: 'Paneer Butter Masala',
    description: 'Paneer in velvety butter-tomato gravy.',
    category: 'main_course_veg',
    price_medium: 110,
    price_large: 170,
    price_per_piece: null,
    medium_label: 'Medium Tray',
    large_label: 'Large Tray',
    image_url:
      'https://lh3.googleusercontent.com/d/1wWhNcmGsIKSpoC2sP03OO2Rd1Xy50v_7=w800',
    is_available: true,
    sort_order: 14,
  },
  {
    id: 'mv15',
    name: 'Paneer Bhurji',
    description: 'Crumbled paneer sautéed with peppers and spices.',
    category: 'main_course_veg',
    price_medium: null,
    price_large: null,
    price_per_piece: null,
    medium_label: 'Medium Tray',
    large_label: 'Large Tray',
    image_url:
      'https://lh3.googleusercontent.com/d/1LKLxoRfUKzXBOkVrAh4Bo_93DZpnR-kF=w800',
    is_available: true,
    sort_order: 15,
  },
  {
    id: 'mv16',
    name: 'Mushroom Mattar / Mattar Mushroom',
    description: 'Mushrooms and peas in creamy gravy.',
    category: 'main_course_veg',
    price_medium: 105,
    price_large: 160,
    price_per_piece: null,
    medium_label: 'Medium Tray',
    large_label: 'Large Tray',
    image_url:
      'https://lh3.googleusercontent.com/d/1dkE2-9cgXy5d2SxFI6Pmm00ghn-xAtoG=w800',
    is_available: true,
    sort_order: 16,
  },
  {
    id: 'mv17',
    name: 'Malai Soya Chaap',
    description: 'Creamy malai-marinated soya chaap pieces.',
    category: 'main_course_veg',
    price_medium: 130,
    price_large: 210,
    price_per_piece: null,
    medium_label: 'Medium Tray',
    large_label: 'Large Tray',
    image_url:
      'https://lh3.googleusercontent.com/d/10SM7ANoNnlisyQc0HY2lUbJ5yOy2-8fx=w800',
    is_available: true,
    sort_order: 17,
  },
  {
    id: 'mv18',
    name: 'Amritsari Nutri',
    description: 'Soya chunks in Amritsari-style spice mix.',
    category: 'main_course_veg',
    price_medium: null,
    price_large: null,
    price_per_piece: null,
    medium_label: 'Medium Tray',
    large_label: 'Large Tray',
    image_url:
      'https://lh3.googleusercontent.com/d/1Kw-RUNvuj0tF4gzh4hKLNFq-9jKWTwqX=w800',
    is_available: true,
    sort_order: 18,
  },
  {
    id: 'mv19',
    name: 'Veg Qeema Mattar',
    description: 'Soya qeema with peas.',
    category: 'main_course_veg',
    price_medium: null,
    price_large: null,
    price_per_piece: null,
    medium_label: 'Medium Tray',
    large_label: 'Large Tray',
    image_url:
      'https://lh3.googleusercontent.com/d/1ojJxxh9K5Qfnou_4BT6F6LW0v9X9u2o9=w800',
    is_available: true,
    sort_order: 19,
  },
  {
    id: 'mv20',
    name: 'Aaloo Mattar (Dry/Curry)',
    description: 'Potato and peas dry or curry style.',
    category: 'main_course_veg',
    price_medium: null,
    price_large: null,
    price_per_piece: null,
    medium_label: 'Medium Tray',
    large_label: 'Large Tray',
    image_url:
      'https://lh3.googleusercontent.com/d/1-lh3wyOj3xXuNhJ28-zafj-UmsYpCDrR=w800',
    is_available: true,
    sort_order: 20,
  },
  {
    id: 'mv21',
    name: 'Mattar Methi Malai',
    description: 'Peas with fenugreek in creamy gravy.',
    category: 'main_course_veg',
    price_medium: null,
    price_large: null,
    price_per_piece: null,
    medium_label: 'Medium Tray',
    large_label: 'Large Tray',
    image_url:
      'https://lh3.googleusercontent.com/d/1-eebLDUSg9LTqYznEaNa530yyCut2NSn=w800',
    is_available: true,
    sort_order: 21,
  },
  {
    id: 'mv22',
    name: 'Bhindi Masala',
    description: 'Crisp okra tossed with onion and spices.',
    category: 'main_course_veg',
    price_medium: 105,
    price_large: 160,
    price_per_piece: null,
    medium_label: 'Medium Tray',
    large_label: 'Large Tray',
    image_url:
      'https://lh3.googleusercontent.com/d/1gkQj6AJhfk2YWKPla0HUESL-cSMVZlDX=w800',
    is_available: true,
    sort_order: 22,
  },
  {
    id: 'mv23',
    name: 'Aaloo Sabzi',
    description: 'Simple home-style potato curry.',
    category: 'main_course_veg',
    price_medium: null,
    price_large: null,
    price_per_piece: null,
    medium_label: 'Medium Tray',
    large_label: 'Large Tray',
    image_url:
      'https://lh3.googleusercontent.com/d/1EKrzDd26oV1oI4Lqg71BJVFPnVYvcnrX=w800',
    is_available: true,
    sort_order: 23,
  },
  {
    id: 'mv24',
    name: 'Choley',
    description: 'Spiced chickpeas Punjab-style.',
    category: 'main_course_veg',
    price_medium: null,
    price_large: null,
    price_per_piece: null,
    medium_label: 'Medium Tray',
    large_label: 'Large Tray',
    image_url:
      'https://lh3.googleusercontent.com/d/1CxJ9ZuIqt-8iAmTxK201V59VKiAuEzBY=w800',
    is_available: true,
    sort_order: 24,
  },
  {
    id: 'mv25',
    name: 'Gatte ki Sabji',
    description: 'Gram-flour dumplings in spiced yogurt curry.',
    category: 'main_course_veg',
    price_medium: null,
    price_large: null,
    price_per_piece: null,
    medium_label: 'Medium Tray',
    large_label: 'Large Tray',
    image_url:
      'https://lh3.googleusercontent.com/d/19M_7pfnMS-vpyO7AIo-4BQ6gH7Bflba_=w800',
    is_available: true,
    sort_order: 25,
  },

  // ── Main Course (Non-Veg) ───────────────────────────────────────
  {
    id: 'mnv1',
    name: 'Egg Bhurji',
    description: 'Indian-style scrambled eggs with spices.',
    category: 'main_course_non_veg',
    price_medium: null,
    price_large: null,
    price_per_piece: null,
    medium_label: 'Medium Tray',
    large_label: 'Large Tray',
    image_url:
      'https://lh3.googleusercontent.com/d/1mbk0J0ImErUVWVsQl0z2KkrMLSkHNY_b=w800',
    is_available: true,
    sort_order: 1,
  },
  {
    id: 'mnv2',
    name: 'Egg Masala',
    description: 'Hard-boiled eggs in spiced onion-tomato gravy.',
    category: 'main_course_non_veg',
    price_medium: null,
    price_large: null,
    price_per_piece: null,
    medium_label: 'Medium Tray',
    large_label: 'Large Tray',
    image_url:
      'https://lh3.googleusercontent.com/d/10Y0q-BMNMk38bER8vxJZzXmMO-ZWXI4f=w800',
    is_available: true,
    sort_order: 2,
  },
  {
    id: 'mnv3',
    name: 'Egg Curry',
    description: 'Eggs simmered in classic curry sauce.',
    category: 'main_course_non_veg',
    price_medium: null,
    price_large: null,
    price_per_piece: null,
    medium_label: 'Medium Tray',
    large_label: 'Large Tray',
    image_url:
      'https://lh3.googleusercontent.com/d/17ukUwtxe5_UOwSBL-SZzwiRfkLaCWY0u=w800',
    is_available: true,
    sort_order: 3,
  },
  {
    id: 'mnv4',
    name: 'Chicken Makhani (Butter Chicken)',
    description: 'Tender chicken in rich tomato-cream-butter gravy.',
    category: 'main_course_non_veg',
    price_medium: 120,
    price_large: 180,
    price_per_piece: null,
    medium_label: 'Medium Tray',
    large_label: 'Large Tray',
    image_url:
      'https://lh3.googleusercontent.com/d/1iLxpojRy2Ds--V-RfubXepxsdw64ar8F=w800',
    is_available: true,
    sort_order: 4,
  },
  {
    id: 'mnv5',
    name: 'Chicken Tikka Masala',
    description: 'Chargrilled chicken in spiced tomato-cream sauce.',
    category: 'main_course_non_veg',
    price_medium: 120,
    price_large: 180,
    price_per_piece: null,
    medium_label: 'Medium Tray',
    large_label: 'Large Tray',
    image_url:
      'https://lh3.googleusercontent.com/d/12HKGfu71igFKoLjziAdX8EBkchuwhOFc=w800',
    is_available: true,
    sort_order: 5,
  },
  {
    id: 'mnv6',
    name: 'Chicken Methi Malai',
    description: 'Chicken in creamy fenugreek-flecked gravy.',
    category: 'main_course_non_veg',
    price_medium: null,
    price_large: null,
    price_per_piece: null,
    medium_label: 'Medium Tray',
    large_label: 'Large Tray',
    image_url:
      'https://lh3.googleusercontent.com/d/1cetonTURnKX65moUe3XZxU2YkLiss3oi=w800',
    is_available: true,
    sort_order: 6,
  },
  {
    id: 'mnv7',
    name: 'Chicken Kali Mirch / Kali Mirch Chicken',
    description: 'Black pepper-forward chicken curry.',
    category: 'main_course_non_veg',
    price_medium: 120,
    price_large: 180,
    price_per_piece: null,
    medium_label: 'Medium Tray',
    large_label: 'Large Tray',
    image_url:
      'https://lh3.googleusercontent.com/d/1f0XtH1GQMNvPJTbckkNOYPsnv2owiTzh=w800',
    is_available: true,
    sort_order: 7,
  },
  {
    id: 'mnv8',
    name: 'Chicken Saag Wala',
    description: 'Chicken in classic spinach gravy.',
    category: 'main_course_non_veg',
    price_medium: 120,
    price_large: 180,
    price_per_piece: null,
    medium_label: 'Medium Tray',
    large_label: 'Large Tray',
    image_url:
      'https://lh3.googleusercontent.com/d/1nmKLsc0RF2U8vR4nnpIXEUithfeyUNdM=w800',
    is_available: true,
    sort_order: 8,
  },
  {
    id: 'mnv9',
    name: 'Chicken Curry / Tari Wala Chicken',
    description: 'Classic home-style chicken curry.',
    category: 'main_course_non_veg',
    price_medium: 120,
    price_large: 180,
    price_per_piece: null,
    medium_label: 'Medium Tray',
    large_label: 'Large Tray',
    image_url:
      'https://lh3.googleusercontent.com/d/1snuq6ryxD9XHG-nKxjPA9t7E1z6Jz33p=w800',
    is_available: true,
    sort_order: 9,
  },
  {
    id: 'mnv10',
    name: 'Chicken Korma',
    description: 'Mild fragrant chicken in creamy yogurt-coconut sauce.',
    category: 'main_course_non_veg',
    price_medium: null,
    price_large: null,
    price_per_piece: null,
    medium_label: 'Medium Tray',
    large_label: 'Large Tray',
    image_url:
      'https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=800',
    is_available: true,
    sort_order: 10,
  },
  {
    id: 'mnv11',
    name: 'Chicken Qeema Mattar',
    description: 'Minced chicken with peas.',
    category: 'main_course_non_veg',
    price_medium: null,
    price_large: null,
    price_per_piece: null,
    medium_label: 'Medium Tray',
    large_label: 'Large Tray',
    image_url:
      'https://lh3.googleusercontent.com/d/1nmA_P-sCB3InnbvtRRZfxSs32MGApclD=w800',
    is_available: true,
    sort_order: 11,
  },
  {
    id: 'mnv12',
    name: 'Chicken Beli Raam / Beliram Chicken',
    description: 'Cashew-and-onion rich chicken curry.',
    category: 'main_course_non_veg',
    price_medium: 130,
    price_large: 190,
    price_per_piece: null,
    medium_label: 'Medium Tray',
    large_label: 'Large Tray',
    image_url:
      'https://lh3.googleusercontent.com/d/1ceGZW1BBcpyqH4RbiaoyzwBVoFlcGyye=w800',
    is_available: true,
    sort_order: 12,
  },
  {
    id: 'mnv13',
    name: 'Hari Mirch Chicken',
    description: 'Spicy green-chili chicken.',
    category: 'main_course_non_veg',
    price_medium: 120,
    price_large: 180,
    price_per_piece: null,
    medium_label: 'Medium Tray',
    large_label: 'Large Tray',
    image_url:
      'https://lh3.googleusercontent.com/d/1xF2ZnLNXXgq2mTE6Dsav000kQHsLFK2v=w800',
    is_available: true,
    sort_order: 13,
  },
  {
    id: 'mnv14',
    name: 'Goat / Lamb Curry / Goat Curry',
    description: 'Slow-cooked goat in aromatic red curry.',
    category: 'main_course_non_veg',
    price_medium: 150,
    price_large: 250,
    price_per_piece: null,
    medium_label: 'Medium Tray',
    large_label: 'Large Tray',
    image_url:
      'https://lh3.googleusercontent.com/d/198pLm-qJZ0reUH_gwS0i8boIink9-Qcs=w800',
    is_available: true,
    sort_order: 14,
  },
  {
    id: 'mnv15',
    name: 'Goat Korma',
    description: 'Mild creamy goat curry.',
    category: 'main_course_non_veg',
    price_medium: null,
    price_large: null,
    price_per_piece: null,
    medium_label: 'Medium Tray',
    large_label: 'Large Tray',
    image_url:
      'https://lh3.googleusercontent.com/d/1aw3e4lKPi0-6bClqdAxSJJMQakzuQg4O=w800',
    is_available: true,
    sort_order: 15,
  },
  {
    id: 'mnv16',
    name: 'Goat Beli Raam',
    description: 'Cashew-rich goat curry.',
    category: 'main_course_non_veg',
    price_medium: null,
    price_large: null,
    price_per_piece: null,
    medium_label: 'Medium Tray',
    large_label: 'Large Tray',
    image_url:
      'https://lh3.googleusercontent.com/d/1H4AFIpdkzQ78khWgvR9_x18x1X0ppCJ_=w800',
    is_available: true,
    sort_order: 16,
  },
  {
    id: 'mnv17',
    name: 'Bhuna Ghosht (Goat)',
    description: 'Dry-roasted goat in bhuna spice mix.',
    category: 'main_course_non_veg',
    price_medium: 150,
    price_large: 250,
    price_per_piece: null,
    medium_label: 'Medium Tray',
    large_label: 'Large Tray',
    image_url:
      'https://lh3.googleusercontent.com/d/1_DOmKVtKGLiAoRRP4jb2u1tNbbRbik5f=w800',
    is_available: true,
    sort_order: 17,
  },

  // ── Biryani Flavors ─────────────────────────────────────────────
  {
    id: 'bf1',
    name: 'Veg Biryani',
    description: 'Layered basmati with veggies and saffron.',
    category: 'biryani_flavors',
    price_medium: null,
    price_large: null,
    price_per_piece: null,
    medium_label: 'Medium Tray',
    large_label: 'Large Tray',
    image_url:
      'https://lh3.googleusercontent.com/d/13R2u0E-R2pxiRbl4D6xnKGhP_5tsXaBt=w800',
    is_available: true,
    sort_order: 1,
  },
  {
    id: 'bf2',
    name: 'Egg Biryani',
    description: 'Boiled egg layered biryani.',
    category: 'biryani_flavors',
    price_medium: null,
    price_large: null,
    price_per_piece: null,
    medium_label: 'Medium Tray',
    large_label: 'Large Tray',
    image_url:
      'https://lh3.googleusercontent.com/d/1lMhPmsiYUNy9RGOyCDaWG0MMl2jZhZB9=w800',
    is_available: true,
    sort_order: 2,
  },
  {
    id: 'bf3',
    name: 'Qeema Biryani',
    description: 'Minced-meat biryani.',
    category: 'biryani_flavors',
    price_medium: null,
    price_large: null,
    price_per_piece: null,
    medium_label: 'Medium Tray',
    large_label: 'Large Tray',
    image_url:
      'https://lh3.googleusercontent.com/d/1IVOUoVMq12GxrGDoDuX322m2QYwsF6nL=w800',
    is_available: true,
    sort_order: 3,
  },
  {
    id: 'bf4',
    name: 'Chicken Biryani',
    description: 'Classic Hyderabadi-style chicken biryani.',
    category: 'biryani_flavors',
    price_medium: null,
    price_large: null,
    price_per_piece: null,
    medium_label: 'Medium Tray',
    large_label: 'Large Tray',
    image_url:
      'https://lh3.googleusercontent.com/d/1ecqlrj70Z5tUJLNEv5OzUOU9CMGrF4LF=w800',
    is_available: true,
    sort_order: 4,
  },
  {
    id: 'bf5',
    name: 'Goat Biryani',
    description: 'Tender goat layered biryani.',
    category: 'biryani_flavors',
    price_medium: null,
    price_large: null,
    price_per_piece: null,
    medium_label: 'Medium Tray',
    large_label: 'Large Tray',
    image_url:
      'https://lh3.googleusercontent.com/d/17nDSugdFX9fNhZjF_f8QW-DVnXlt8M9z=w800',
    is_available: true,
    sort_order: 5,
  },

  // ── Rice ────────────────────────────────────────────────────────
  {
    id: 'ri1',
    name: 'Plain Rice / White Rice',
    description: 'Steamed long-grain basmati.',
    category: 'rice',
    price_medium: 50,
    price_large: 70,
    price_per_piece: null,
    medium_label: 'Medium Tray',
    large_label: 'Large Tray',
    image_url:
      'https://lh3.googleusercontent.com/d/1C589kWFgZXh2NeKAK1V9gRPDSWmTXX-D=w800',
    is_available: true,
    sort_order: 1,
  },
  {
    id: 'ri2',
    name: 'Jeera Rice',
    description: 'Basmati rice tempered with cumin.',
    category: 'rice',
    price_medium: 50,
    price_large: 70,
    price_per_piece: null,
    medium_label: 'Medium Tray',
    large_label: 'Large Tray',
    image_url:
      'https://lh3.googleusercontent.com/d/16TIinO52Wn_8Vq6_dg8Kl2fRjt3DdcFN=w800',
    is_available: true,
    sort_order: 2,
  },
  {
    id: 'ri3',
    name: 'Mattar Pulao',
    description: 'Pea pulao.',
    category: 'rice',
    price_medium: null,
    price_large: null,
    price_per_piece: null,
    medium_label: 'Medium Tray',
    large_label: 'Large Tray',
    image_url:
      'https://lh3.googleusercontent.com/d/19uqm3jfKUJ2wgnwFi5gfUem13HayZ-Ho=w800',
    is_available: true,
    sort_order: 3,
  },
  {
    id: 'ri4',
    name: 'Veg Pulao',
    description: 'Mixed-veggie basmati pulao.',
    category: 'rice',
    price_medium: null,
    price_large: null,
    price_per_piece: null,
    medium_label: 'Medium Tray',
    large_label: 'Large Tray',
    image_url:
      'https://lh3.googleusercontent.com/d/1evjObQw4uMSvEF9kFI_i14TCDwYOxZKX=w800',
    is_available: true,
    sort_order: 4,
  },
  {
    id: 'ri5',
    name: 'Yellow Rice',
    description: 'Saffron-tinted basmati.',
    category: 'rice',
    price_medium: 50,
    price_large: 70,
    price_per_piece: null,
    medium_label: 'Medium Tray',
    large_label: 'Large Tray',
    image_url:
      'https://lh3.googleusercontent.com/d/1AqLQPrCxHCLbO2Y8Una9AwudWa2GArym=w800',
    is_available: true,
    sort_order: 5,
  },
  {
    id: 'ri6',
    name: 'Matar Rice',
    description: 'Basmati with peas.',
    category: 'rice',
    price_medium: 50,
    price_large: 70,
    price_per_piece: null,
    medium_label: 'Medium Tray',
    large_label: 'Large Tray',
    image_url:
      'https://images.unsplash.com/photo-1596560548464-f010549b84d7?w=800',
    is_available: true,
    sort_order: 6,
  },

  // ── Salad ───────────────────────────────────────────────────────
  {
    id: 'sa1',
    name: 'Green Salad',
    description: 'Cucumber, tomato, onion, lemon.',
    category: 'salad',
    price_medium: 50,
    price_large: 70,
    price_per_piece: null,
    medium_label: 'Medium Tray',
    large_label: 'Large Tray',
    image_url:
      'https://lh3.googleusercontent.com/d/1dNq4BQFSjoxRTvl-oOOcmvW1OYLvydcQ=w800',
    is_available: true,
    sort_order: 1,
  },
  {
    id: 'sa2',
    name: 'Chop Green Salad',
    description: 'Finely chopped mixed greens with house vinaigrette.',
    category: 'salad',
    price_medium: 50,
    price_large: 70,
    price_per_piece: null,
    medium_label: 'Medium Tray',
    large_label: 'Large Tray',
    image_url:
      'https://lh3.googleusercontent.com/d/1zsvv6FeoCyRvNAt2xwVfIp_tIIpw_56S=w800',
    is_available: true,
    sort_order: 2,
  },

  // ── Italian ─────────────────────────────────────────────────────
  {
    id: 'it1',
    name: 'White Sauce Pasta',
    description: 'Penne in creamy white sauce.',
    category: 'italian',
    price_medium: 50,
    price_large: 70,
    price_per_piece: null,
    medium_label: 'Medium Tray',
    large_label: 'Large Tray',
    image_url:
      'https://lh3.googleusercontent.com/d/1QOMuTur4IOtd_hAMVcPcxE_zG6FPdKtH=w800',
    is_available: true,
    sort_order: 1,
  },
  {
    id: 'it2',
    name: 'Cheesy White Sauce Pasta',
    description: 'Penne in cheesy white sauce.',
    category: 'italian',
    price_medium: 55,
    price_large: 75,
    price_per_piece: null,
    medium_label: 'Medium Tray',
    large_label: 'Large Tray',
    image_url:
      'https://lh3.googleusercontent.com/d/1n0EEGWZBhH7ouRQMduXmR-sPceDb9rU-=w800',
    is_available: true,
    sort_order: 2,
  },
  {
    id: 'it3',
    name: 'Mushroom White Sauce Pasta',
    description: 'White-sauce pasta with mushrooms.',
    category: 'italian',
    price_medium: 55,
    price_large: 75,
    price_per_piece: null,
    medium_label: 'Medium Tray',
    large_label: 'Large Tray',
    image_url:
      'https://lh3.googleusercontent.com/d/1wTuliDcmtMC1CyPn8TwJvLq7ydpeztTK=w800',
    is_available: true,
    sort_order: 3,
  },
  {
    id: 'it4',
    name: 'Alfredo Pasta',
    description: 'Classic creamy parmesan alfredo.',
    category: 'italian',
    price_medium: 50,
    price_large: 70,
    price_per_piece: null,
    medium_label: 'Medium Tray',
    large_label: 'Large Tray',
    image_url:
      'https://images.unsplash.com/photo-1645112411341-6c4fd023714a?w=800',
    is_available: true,
    sort_order: 4,
  },
  {
    id: 'it5',
    name: 'Chicken Alfredo Pasta',
    description: 'Chicken breast in creamy alfredo sauce.',
    category: 'italian',
    price_medium: 55,
    price_large: 75,
    price_per_piece: null,
    medium_label: 'Medium Tray',
    large_label: 'Large Tray',
    image_url:
      'https://lh3.googleusercontent.com/d/1S7f7ceo5UMELCA4pM40Ar9YwmeNDD1_A=w800',
    is_available: true,
    sort_order: 5,
  },
  {
    id: 'it6',
    name: 'Cheesy Chicken Alfredo Pasta',
    description: 'Loaded cheese chicken alfredo.',
    category: 'italian',
    price_medium: 60,
    price_large: 80,
    price_per_piece: null,
    medium_label: 'Medium Tray',
    large_label: 'Large Tray',
    image_url:
      'https://lh3.googleusercontent.com/d/1ks0vQqDZMPE_aYK0Ovmh5hFHJ9VCUbYv=w800',
    is_available: true,
    sort_order: 6,
  },
  {
    id: 'it7',
    name: 'Red Sauce Pasta',
    description: 'Penne in tangy tomato sauce.',
    category: 'italian',
    price_medium: 50,
    price_large: 70,
    price_per_piece: null,
    medium_label: 'Medium Tray',
    large_label: 'Large Tray',
    image_url:
      'https://lh3.googleusercontent.com/d/1vvMLmzOgfe6zVWkJc8ep1163X4w-ua0D=w800',
    is_available: true,
    sort_order: 7,
  },

  // ── Indo-Chinese ────────────────────────────────────────────────
  {
    id: 'ic1',
    name: 'Veg Fried Rice',
    description: 'Wok-tossed rice with veggies and soy.',
    category: 'indo_chinese',
    price_medium: 55,
    price_large: 75,
    price_per_piece: null,
    medium_label: 'Medium Tray',
    large_label: 'Large Tray',
    image_url:
      'https://lh3.googleusercontent.com/d/1BygZRfhzxocPwMawCyfIkHdY9qIIvAi7=w800',
    is_available: true,
    sort_order: 1,
  },
  {
    id: 'ic2',
    name: 'Egg Fried Rice',
    description: 'Fried rice with scrambled egg.',
    category: 'indo_chinese',
    price_medium: null,
    price_large: null,
    price_per_piece: null,
    medium_label: 'Medium Tray',
    large_label: 'Large Tray',
    image_url:
      'https://lh3.googleusercontent.com/d/1zD5sMQS0tSyViA8rYFidx8U17a7VPmoI=w800',
    is_available: true,
    sort_order: 2,
  },
  {
    id: 'ic3',
    name: 'Chicken Fried Rice',
    description: 'Wok-tossed rice with chicken.',
    category: 'indo_chinese',
    price_medium: 60,
    price_large: 80,
    price_per_piece: null,
    medium_label: 'Medium Tray',
    large_label: 'Large Tray',
    image_url:
      'https://lh3.googleusercontent.com/d/15MrqwNE-2U9paP_hibNf6Zg6FL0lLjMM=w800',
    is_available: true,
    sort_order: 3,
  },
  {
    id: 'ic4',
    name: 'Shrimp Fried Rice',
    description: 'Wok-tossed rice with shrimp.',
    category: 'indo_chinese',
    price_medium: 80,
    price_large: 120,
    price_per_piece: null,
    medium_label: 'Medium Tray',
    large_label: 'Large Tray',
    image_url:
      'https://lh3.googleusercontent.com/d/1pdQsJpTDoZ2yImNAedbGBLyCxSLEdQ0E=w800',
    is_available: true,
    sort_order: 4,
  },
  {
    id: 'ic5',
    name: 'Veg Chow Mein',
    description: 'Stir-fried noodles with veggies.',
    category: 'indo_chinese',
    price_medium: 55,
    price_large: 75,
    price_per_piece: null,
    medium_label: 'Medium Tray',
    large_label: 'Large Tray',
    image_url:
      'https://lh3.googleusercontent.com/d/1lmgF8I1xwl9KINz-HjY6fvtZIH-lmucc=w800',
    is_available: true,
    sort_order: 5,
  },
  {
    id: 'ic6',
    name: 'Egg Chow Mein',
    description: 'Stir-fried noodles with egg.',
    category: 'indo_chinese',
    price_medium: null,
    price_large: null,
    price_per_piece: null,
    medium_label: 'Medium Tray',
    large_label: 'Large Tray',
    image_url:
      'https://lh3.googleusercontent.com/d/1CAUzjShZDIAB6oYtTSuNdXQ6fkEh70o0=w800',
    is_available: true,
    sort_order: 6,
  },
  {
    id: 'ic7',
    name: 'Chicken Chow Mein',
    description: 'Stir-fried noodles with chicken.',
    category: 'indo_chinese',
    price_medium: 60,
    price_large: 80,
    price_per_piece: null,
    medium_label: 'Medium Tray',
    large_label: 'Large Tray',
    image_url:
      'https://lh3.googleusercontent.com/d/1ikqEkoQx6KERGR81urnVPHRIXWM6IrTE=w800',
    is_available: true,
    sort_order: 7,
  },
  {
    id: 'ic8',
    name: 'Veg Hakka Noodles',
    description: 'Wok-tossed hakka noodles with veggies.',
    category: 'indo_chinese',
    price_medium: 60,
    price_large: 80,
    price_per_piece: null,
    medium_label: 'Medium Tray',
    large_label: 'Large Tray',
    image_url:
      'https://lh3.googleusercontent.com/d/1BIVmUsFZKdpEl6u9S5HlzOZjHF7vw9K8=w800',
    is_available: true,
    sort_order: 8,
  },
  {
    id: 'ic9',
    name: 'Chicken Hakka Noodles',
    description: 'Hakka noodles with chicken.',
    category: 'indo_chinese',
    price_medium: 60,
    price_large: 80,
    price_per_piece: null,
    medium_label: 'Medium Tray',
    large_label: 'Large Tray',
    image_url:
      'https://lh3.googleusercontent.com/d/1r9ntc433Pi3a7r0oc3BEXU_tR-uf7z7n=w800',
    is_available: true,
    sort_order: 9,
  },
  {
    id: 'ic10',
    name: 'Shrimp Hakka Noodles',
    description: 'Hakka noodles with shrimp.',
    category: 'indo_chinese',
    price_medium: 80,
    price_large: 120,
    price_per_piece: null,
    medium_label: 'Medium Tray',
    large_label: 'Large Tray',
    image_url:
      'https://lh3.googleusercontent.com/d/17LNRApLUsCIWPC6A8bqxiUE2sd7XDoup=w800',
    is_available: true,
    sort_order: 10,
  },
  {
    id: 'ic11',
    name: 'Veg Manchurian (Dry/Gravy)',
    description: 'Veggie balls in soy-ginger sauce.',
    category: 'indo_chinese',
    price_medium: 65,
    price_large: 95,
    price_per_piece: null,
    medium_label: 'Medium Tray',
    large_label: 'Large Tray',
    image_url:
      'https://lh3.googleusercontent.com/d/1VeE0MBc0LHaCZPcSjRlg_i8_X4TKoKls=w800',
    is_available: true,
    sort_order: 11,
  },
  {
    id: 'ic12',
    name: 'Chicken Manchurian (Dry/Gravy)',
    description: 'Crispy chicken in soy-ginger sauce.',
    category: 'indo_chinese',
    price_medium: 75,
    price_large: 110,
    price_per_piece: null,
    medium_label: 'Medium Tray',
    large_label: 'Large Tray',
    image_url:
      'https://images.unsplash.com/photo-1606491956689-2ea866880c84?w=800',
    is_available: true,
    sort_order: 12,
  },
  {
    id: 'ic13',
    name: 'Chilli Chicken (Dry/Gravy)',
    description: 'Battered chicken in spicy Indo-Chinese chilli sauce.',
    category: 'indo_chinese',
    price_medium: 90,
    price_large: 140,
    price_per_piece: null,
    medium_label: 'Medium Tray',
    large_label: 'Large Tray',
    image_url:
      'https://lh3.googleusercontent.com/d/1XDWqtLTbpF16jmi3EJ2UqrjJk0VMyoJt=w800',
    is_available: true,
    sort_order: 13,
  },
  {
    id: 'ic14',
    name: 'Chilli Paneer (Dry/Gravy)',
    description: 'Crispy paneer in spicy chilli sauce.',
    category: 'indo_chinese',
    price_medium: 65,
    price_large: 85,
    price_per_piece: null,
    medium_label: 'Medium Tray',
    large_label: 'Large Tray',
    image_url:
      'https://lh3.googleusercontent.com/d/1rlf1gOU9X5d_t735gMxpLircoUJxSnDL=w800',
    is_available: true,
    sort_order: 14,
  },
  {
    id: 'ic15',
    name: 'Chicken 65',
    description: 'Spicy deep-fried chicken bites in curry-leaf tempering.',
    category: 'indo_chinese',
    price_medium: null,
    price_large: null,
    price_per_piece: null,
    medium_label: 'Medium Tray',
    large_label: 'Large Tray',
    image_url:
      'https://lh3.googleusercontent.com/d/1eTEaEsL7EZ2tcy875o28uKtus0I_Vxrf=w800',
    is_available: true,
    sort_order: 15,
  },

  // ── Tandoori Treasures ──────────────────────────────────────────
  {
    id: 'tt1',
    name: 'Paneer Tikka',
    description: 'Chargrilled paneer skewers.',
    category: 'tandoori_treasures',
    price_medium: null,
    price_large: null,
    price_per_piece: null,
    medium_label: 'Medium Tray',
    large_label: 'Large Tray',
    image_url:
      'https://lh3.googleusercontent.com/d/1JQ9wIIG-qA9ziKbFFtn_RSBBB9NrNUL3=w800',
    is_available: true,
    sort_order: 1,
  },
  {
    id: 'tt2',
    name: 'Mushroom Tikka',
    description: 'Chargrilled mushroom skewers.',
    category: 'tandoori_treasures',
    price_medium: null,
    price_large: null,
    price_per_piece: null,
    medium_label: 'Medium Tray',
    large_label: 'Large Tray',
    image_url:
      'https://lh3.googleusercontent.com/d/1ZDk3YvlfLnkywY96RWNn4WEvHAVY6OWB=w800',
    is_available: true,
    sort_order: 2,
  },
  {
    id: 'tt3',
    name: 'Pineapple Tikka',
    description: 'Chargrilled pineapple wedges.',
    category: 'tandoori_treasures',
    price_medium: null,
    price_large: null,
    price_per_piece: null,
    medium_label: 'Medium Tray',
    large_label: 'Large Tray',
    image_url:
      'https://lh3.googleusercontent.com/d/1JqsMTjHqhWwipaVe0fE4OEMKJGQh1w_3=w800',
    is_available: true,
    sort_order: 3,
  },
  {
    id: 'tt4',
    name: 'Chicken Tikka',
    description: 'Yogurt-marinated chargrilled chicken skewers.',
    category: 'tandoori_treasures',
    price_medium: 110,
    price_large: 190,
    price_per_piece: null,
    medium_label: 'Medium Tray',
    large_label: 'Large Tray',
    image_url:
      'https://lh3.googleusercontent.com/d/1kFBePvHd5WpkGAbe79aecwWDPvKpdi1U=w800',
    is_available: true,
    sort_order: 4,
  },
  {
    id: 'tt5',
    name: 'Tandoori Chicken Tikka',
    description: 'Classic tandoori-style chicken tikka.',
    category: 'tandoori_treasures',
    price_medium: null,
    price_large: null,
    price_per_piece: null,
    medium_label: 'Medium Tray',
    large_label: 'Large Tray',
    image_url:
      'https://lh3.googleusercontent.com/d/1JWxV6Iq23vuMlFlg3N9lJBuQbR6pnu3A=w800',
    is_available: true,
    sort_order: 5,
  },
  {
    id: 'tt6',
    name: 'Chicken Malai Tikka',
    description: 'Creamy mild chicken tikka.',
    category: 'tandoori_treasures',
    price_medium: 110,
    price_large: 190,
    price_per_piece: null,
    medium_label: 'Medium Tray',
    large_label: 'Large Tray',
    image_url:
      'https://lh3.googleusercontent.com/d/14qg_aJoA5dohm1qeaAyyXDIg-jSgXK7h=w800',
    is_available: true,
    sort_order: 6,
  },
  {
    id: 'tt7',
    name: 'Lehsuni Tikka',
    description: 'Garlic-loaded juicy chicken tikka.',
    category: 'tandoori_treasures',
    price_medium: 110,
    price_large: 190,
    price_per_piece: null,
    medium_label: 'Medium Tray',
    large_label: 'Large Tray',
    image_url:
      'https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=800',
    is_available: true,
    sort_order: 7,
  },
  {
    id: 'tt8',
    name: 'Chicken Tandoori (WB)',
    description: 'West Bengal-style tandoori chicken.',
    category: 'tandoori_treasures',
    price_medium: 120,
    price_large: 210,
    price_per_piece: null,
    medium_label: 'Medium Tray',
    large_label: 'Large Tray',
    image_url:
      'https://lh3.googleusercontent.com/d/1rNA60w0dGDiM6CkRre2hPTc3yhaLXokj=w800',
    is_available: true,
    sort_order: 8,
  },

  // ── Chef's Specials ─────────────────────────────────────────────
  {
    id: 'cs1',
    name: 'Poori',
    description: 'Fluffy deep-fried whole-wheat bread.',
    category: 'chefs_specials',
    price_medium: null,
    price_large: null,
    price_per_piece: null,
    medium_label: 'Medium Tray',
    large_label: 'Large Tray',
    image_url:
      'https://lh3.googleusercontent.com/d/1tqHt3_fC9vh1h3yKDky4Z5e93nRg5keD=w800',
    is_available: true,
    sort_order: 1,
  },
  {
    id: 'cs2',
    name: 'Bhature',
    description: 'Fluffy deep-fried maida bread.',
    category: 'chefs_specials',
    price_medium: null,
    price_large: null,
    price_per_piece: null,
    medium_label: 'Medium Tray',
    large_label: 'Large Tray',
    image_url:
      'https://lh3.googleusercontent.com/d/14vZwNqv3fVJxCGYY_qyyRVyDrslczmcg=w800',
    is_available: true,
    sort_order: 2,
  },
  {
    id: 'cs3',
    name: 'Pao Bhaji',
    description: 'Spiced mashed vegs with butter-toasted buns.',
    category: 'chefs_specials',
    price_medium: null,
    price_large: null,
    price_per_piece: null,
    medium_label: 'Medium Tray',
    large_label: 'Large Tray',
    image_url:
      'https://lh3.googleusercontent.com/d/1w2ege2Dr-pvUrZnaWuG-fBoP21G49oBz=w800',
    is_available: true,
    sort_order: 3,
  },
  {
    id: 'cs4',
    name: 'Veg Puff Patties',
    description: 'Flaky pastry with spiced veggies. Sold per piece.',
    category: 'chefs_specials',
    price_medium: null,
    price_large: null,
    price_per_piece: 4,
    medium_label: null,
    large_label: null,
    image_url:
      'https://lh3.googleusercontent.com/d/1L9BWMuQWBGxy7BvNz6QmBUsvqZIwMmyp=w800',
    is_available: true,
    sort_order: 4,
  },
  {
    id: 'cs5',
    name: 'Chicken Matki',
    description: 'Chicken in tomato-onion masala.',
    category: 'chefs_specials',
    price_medium: null,
    price_large: null,
    price_per_piece: null,
    medium_label: 'Medium Tray',
    large_label: 'Large Tray',
    image_url:
      'https://lh3.googleusercontent.com/d/1iJYZ-VWNbd1gpxvVoGf5C8m1ljH-328J=w800',
    is_available: true,
    sort_order: 5,
  },
  {
    id: 'cs6',
    name: 'Chicken Puff Patties',
    description: 'Flaky pastry stuffed with spiced chicken. Sold per piece.',
    category: 'chefs_specials',
    price_medium: null,
    price_large: null,
    price_per_piece: 5,
    medium_label: null,
    large_label: null,
    image_url:
      'https://lh3.googleusercontent.com/d/19CWbafnETegIKS0ucmsMZZ90AlUflTEb=w800',
    is_available: true,
    sort_order: 6,
  },
  {
    id: 'cs7',
    name: 'Qeema Puff Patties',
    description: 'Flaky pastry stuffed with minced meat. Sold per piece.',
    category: 'chefs_specials',
    price_medium: null,
    price_large: null,
    price_per_piece: 5,
    medium_label: null,
    large_label: null,
    image_url:
      'https://lh3.googleusercontent.com/d/1DyKosPOJ9qj-tlANBCNEVayYi02a2UNV=w800',
    is_available: true,
    sort_order: 7,
  },

  {
    id: 'av5',
    name: 'Paneer Puff Patties',
    description: 'Flaky pastry stuffed with spiced paneer. Sold per piece.',
    category: 'appetizers_veg',
    price_medium: null,
    price_large: null,
    price_per_piece: 4,
    medium_label: null,
    large_label: null,
    image_url:
      'https://lh3.googleusercontent.com/d/1gX7ZSgZIefzlR8xA8sJOqG7_6xrhSBOV=w800',
    is_available: true,
    sort_order: 5,
  },
];
