export const CONTACT = {
  phone: '(443) 547-1326',
  phoneRaw: '+14435471326',
  whatsappRaw: '14435471326',
  email: 'trendycheff@gmail.com',
  chef: 'Trendy Cheff',
  location: 'Maryland',
};

export const CATEGORIES = [
  { id: 'appetizers_non_veg', label: 'Appetizers (Non-Veg)' },
  { id: 'appetizers_veg', label: 'Appetizers (Veg)' },
  { id: 'biryani_flavors', label: 'Biryani Flavors' },
  { id: 'chefs_specials', label: "Chef's Specials" },
  { id: 'indo_chinese', label: 'Indo-Chinese' },
  { id: 'italian', label: 'Italian' },
  { id: 'main_course_non_veg', label: 'Main Course (Non-Veg)' },
  { id: 'main_course_veg', label: 'Main Course (Veg)' },
  { id: 'rice', label: 'Rice' },
  { id: 'salad', label: 'Salad' },
  { id: 'tandoori_treasures', label: 'Tandoori Treasures' },
];


export const DELIVERY_FEE = 25;
export const SMALL_TRAY_MULTIPLIER = 0.65;

export const PAYMENT_METHODS = [
  { id: 'square_card', label: 'Pay with card' },
  { id: 'paypal', label: 'PayPal' },
  { id: 'venmo', label: 'Venmo' },
  { id: 'cashapp', label: 'Cash App' },
];

const SUPABASE =
  'https://agjfydkixmeobxpzpfqt.supabase.co/storage/v1/object/public/menu-photos/';

export const SAMPLE_MENU = [
  {
    id: 'mv7',
    name: 'Aaloo Gobi',
    description: 'Potato and cauliflower with turmeric and ginger.',
    category: 'main_course_veg',
    price_medium: null,
    price_large: null,
    price_per_piece: null,
    medium_label: 'Medium Tray',
    large_label: 'Large Tray',
    image_url: SUPABASE + 'Aloo%20Gobhi.png',
    is_available: true,
    sort_order: 1,
  },
  {
    id: 'mv20',
    name: 'Aaloo Mattar (Dry/Curry)',
    description: 'Potato and peas dry or curry style.',
    category: 'main_course_veg',
    price_medium: null,
    price_large: null,
    price_per_piece: null,
    medium_label: 'Medium Tray',
    large_label: 'Large Tray',
    image_url: SUPABASE + 'Alu%20Matar.jpg',
    is_available: true,
    sort_order: 2,
  },
  {
    id: 'mv23',
    name: 'Aaloo Sabzi',
    description: 'Simple home-style potato curry.',
    category: 'main_course_veg',
    price_medium: null,
    price_large: null,
    price_per_piece: null,
    medium_label: 'Medium Tray',
    large_label: 'Large Tray',
    image_url: SUPABASE + 'Aloo%20Sabzi.png',
    is_available: true,
    sort_order: 3,
  },
  {
    id: 'it4',
    name: 'Alfredo Pasta',
    description: 'Classic creamy parmesan alfredo.',
    category: 'italian',
    price_medium: 50,
    price_large: 70,
    price_per_piece: null,
    medium_label: 'Medium Tray',
    large_label: 'Large Tray',
    image_url:
      'https://images.unsplash.com/photo-1645112411341-6c4fd023714a?w=800',
    is_available: true,
    sort_order: 4,
  },
  {
    id: 'av3',
    name: 'Alu Ki Sabzi / Kachori',
    description: 'Fluffy kachori with spiced potato curry.',
    category: 'appetizers_veg',
    price_medium: 75,
    price_large: 130,
    price_per_piece: null,
    medium_label: 'Medium Tray',
    large_label: 'Large Tray',
    image_url: SUPABASE + 'Alu%20Kachori.png',
    is_available: true,
    sort_order: 5,
  },
  {
    id: 'av4',
    name: 'Aloo Puff Patties',
    description:
      'Flaky pastry stuffed with spiced vegetables. Sold per piece.',
    category: 'appetizers_veg',
    price_medium: null,
    price_large: null,
    price_per_piece: 4,
    medium_label: null,
    large_label: null,
    image_url: SUPABASE + 'Veg%20Puff%20Patties%20.png',
    is_available: true,
    sort_order: 6,
  },
  {
    id: 'cs4',
    name: 'Aloo Puff Patties',
    description: 'Flaky pastry with spiced veggies. Sold per piece.',
    category: 'chefs_specials',
    price_medium: null,
    price_large: null,
    price_per_piece: 4,
    medium_label: null,
    large_label: null,
    image_url: SUPABASE + 'Veg%20Puff%20Patties%20.png',
    is_available: true,
    sort_order: 7,
  },
  {
    id: 'mv18',
    name: 'Amritsari Nutri',
    description: 'Soya chunks in Amritsari-style spice mix.',
    category: 'main_course_veg',
    price_medium: null,
    price_large: null,
    price_per_piece: null,
    medium_label: 'Medium Tray',
    large_label: 'Large Tray',
    image_url: SUPABASE + 'Amritsari%20Nutrie.jpg',
    is_available: true,
    sort_order: 8,
  },
  {
    id: 'mv8',
    name: 'Baingan Bharta',
    description: 'Smoky mashed roasted eggplant with spices.',
    category: 'main_course_veg',
    price_medium: 105,
    price_large: 160,
    price_per_piece: null,
    medium_label: 'Medium Tray',
    large_label: 'Large Tray',
    image_url: SUPABASE + 'Baingan%20Bharta.png',
    is_available: true,
    sort_order: 9,
  },
  {
    id: 'cs2',
    name: 'Bhature',
    description: 'Fluffy deep-fried maida bread.',
    category: 'chefs_specials',
    price_medium: null,
    price_large: null,
    price_per_piece: null,
    medium_label: 'Medium Tray',
    large_label: 'Large Tray',
    image_url: SUPABASE + 'Bhature.png',
    is_available: true,
    sort_order: 10,
  },
  {
    id: 'mv22',
    name: 'Bhindi Masala',
    description: 'Crisp okra tossed with onion and spices.',
    category: 'main_course_veg',
    price_medium: 105,
    price_large: 160,
    price_per_piece: null,
    medium_label: 'Medium Tray',
    large_label: 'Large Tray',
    image_url: SUPABASE + 'Bhindi%20Masala.png',
    is_available: true,
    sort_order: 11,
  },
  {
    id: 'mnv17',
    name: 'Bhuna Ghosht (Goat)',
    description: 'Dry-roasted goat in bhuna spice mix.',
    category: 'main_course_non_veg',
    price_medium: 150,
    price_large: 250,
    price_per_piece: null,
    medium_label: 'Medium Tray',
    large_label: 'Large Tray',
    image_url: SUPABASE + 'Bhuna%20Ghosht.png',
    is_available: true,
    sort_order: 12,
  },
  {
    id: 'mv4',
    name: 'Chana Masala',
    description: 'Spiced chickpeas in classic North-Indian masala.',
    category: 'main_course_veg',
    price_medium: 105,
    price_large: 160,
    price_per_piece: null,
    medium_label: 'Medium Tray',
    large_label: 'Large Tray',
    image_url: SUPABASE + 'Chana%20Masala.png',
    is_available: true,
    sort_order: 13,
  },
  {
    id: 'it6',
    name: 'Cheesy Chicken Alfredo Pasta',
    description: 'Loaded cheese chicken alfredo.',
    category: 'italian',
    price_medium: 60,
    price_large: 80,
    price_per_piece: null,
    medium_label: 'Medium Tray',
    large_label: 'Large Tray',
    image_url: SUPABASE + 'Cheesy%20Chicken%20Alfredo%20Pasta%20.png',
    is_available: true,
    sort_order: 14,
  },
  {
    id: 'it2',
    name: 'Cheesy White Sauce Pasta',
    description: 'Penne in cheesy white sauce.',
    category: 'italian',
    price_medium: 55,
    price_large: 75,
    price_per_piece: null,
    medium_label: 'Medium Tray',
    large_label: 'Large Tray',
    image_url: SUPABASE + 'Cheesy%20White%20Sauce%20Pasta%20.png',
    is_available: true,
    sort_order: 15,
  },
  {
    id: 'ic15',
    name: 'Chicken 65',
    description:
      'Spicy deep-fried chicken bites in curry-leaf tempering.',
    category: 'indo_chinese',
    price_medium: null,
    price_large: null,
    price_per_piece: null,
    medium_label: 'Medium Tray',
    large_label: 'Large Tray',
    image_url: SUPABASE + 'Chicken%2065.png',
    is_available: true,
    sort_order: 16,
  },
  {
    id: 'it5',
    name: 'Chicken Alfredo Pasta',
    description: 'Chicken breast in creamy alfredo sauce.',
    category: 'italian',
    price_medium: 55,
    price_large: 75,
    price_per_piece: null,
    medium_label: 'Medium Tray',
    large_label: 'Large Tray',
    image_url: SUPABASE + 'Chicken%20Alfredo%20Pasta.png',
    is_available: true,
    sort_order: 17,
  },
  {
    id: 'mnv12',
    name: 'Chicken Beli Raam / Beliram Chicken',
    description: 'Cashew-and-onion rich chicken curry.',
    category: 'main_course_non_veg',
    price_medium: 130,
    price_large: 190,
    price_per_piece: null,
    medium_label: 'Medium Tray',
    large_label: 'Large Tray',
    image_url: SUPABASE + 'Chicken%20Beli%20Raam.png',
    is_available: true,
    sort_order: 18,
  },
  {
    id: 'bf4',
    name: 'Chicken Biryani',
    description: 'Classic Hyderabadi-style chicken biryani.',
    category: 'biryani_flavors',
    price_medium: null,
    price_large: null,
    price_per_piece: null,
    medium_label: 'Medium Tray',
    large_label: 'Large Tray',
    image_url: SUPABASE + 'Chicken%20Biryani.png',
    is_available: true,
    sort_order: 19,
  },
  {
    id: 'ic7',
    name: 'Chicken Chow Mein',
    description: 'Stir-fried noodles with chicken.',
    category: 'indo_chinese',
    price_medium: 60,
    price_large: 80,
    price_per_piece: null,
    medium_label: 'Medium Tray',
    large_label: 'Large Tray',
    image_url: SUPABASE + 'Chicken%20Chowmein.png',
    is_available: true,
    sort_order: 20,
  },
  {
    id: 'mnv9',
    name: 'Chicken Curry / Tari Wala Chicken',
    description: 'Classic home-style chicken curry.',
    category: 'main_course_non_veg',
    price_medium: 120,
    price_large: 180,
    price_per_piece: null,
    medium_label: 'Medium Tray',
    large_label: 'Large Tray',
    image_url: SUPABASE + 'Chicken%20Curry.png',
    is_available: true,
    sort_order: 21,
  },
  {
    id: 'ic3',
    name: 'Chicken Fried Rice',
    description: 'Wok-tossed rice with chicken.',
    category: 'indo_chinese',
    price_medium: 60,
    price_large: 80,
    price_per_piece: null,
    medium_label: 'Medium Tray',
    large_label: 'Large Tray',
    image_url: SUPABASE + 'Chicken%20Fried%20Rice.png',
    is_available: true,
    sort_order: 22,
  },
  {
    id: 'ic9',
    name: 'Chicken Hakka Noodles',
    description: 'Hakka noodles with chicken.',
    category: 'indo_chinese',
    price_medium: 60,
    price_large: 80,
    price_per_piece: null,
    medium_label: 'Medium Tray',
    large_label: 'Large Tray',
    image_url: SUPABASE + 'Chicken%20Hakka%20Noodles.png',
    is_available: true,
    sort_order: 23,
  },
  {
    id: 'mnv7',
    name: 'Chicken Kali Mirch / Kali Mirch Chicken',
    description: 'Black pepper-forward chicken curry.',
    category: 'main_course_non_veg',
    price_medium: 120,
    price_large: 180,
    price_per_piece: null,
    medium_label: 'Medium Tray',
    large_label: 'Large Tray',
    image_url: SUPABASE + 'Chicken%20Kali%20Mirch.png',
    is_available: true,
    sort_order: 24,
  },
  {
    id: 'mnv10',
    name: 'Chicken Korma',
    description: 'Mild fragrant chicken in creamy yogurt-coconut sauce.',
    category: 'main_course_non_veg',
    price_medium: null,
    price_large: null,
    price_per_piece: null,
    medium_label: 'Medium Tray',
    large_label: 'Large Tray',
    image_url:
      'https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=800',
    is_available: true,
    sort_order: 25,
  },
  {
    id: 'mnv4',
    name: 'Chicken Makhani (Butter Chicken)',
    description: 'Tender chicken in rich tomato-cream-butter gravy.',
    category: 'main_course_non_veg',
    price_medium: 120,
    price_large: 180,
    price_per_piece: null,
    medium_label: 'Medium Tray',
    large_label: 'Large Tray',
    image_url: SUPABASE + 'butter%20chicken.png',
    is_available: true,
    sort_order: 26,
  },
  {
    id: 'anv4',
    name: 'Chicken Malai Tikka',
    description: 'Creamy mild chicken tikka with malai marinade.',
    category: 'appetizers_non_veg',
    price_medium: 110,
    price_large: 190,
    price_per_piece: null,
    medium_label: 'Medium Tray',
    large_label: 'Large Tray',
    image_url: SUPABASE + 'Chicken%20Malai%20Tikka.png',
    is_available: true,
    sort_order: 27,
  },
  {
    id: 'tt6',
    name: 'Chicken Malai Tikka',
    description: 'Creamy mild chicken tikka.',
    category: 'tandoori_treasures',
    price_medium: 110,
    price_large: 190,
    price_per_piece: null,
    medium_label: 'Medium Tray',
    large_label: 'Large Tray',
    image_url: SUPABASE + 'Chicken%20Malai%20Tikka.png',
    is_available: true,
    sort_order: 28,
  },
  {
    id: 'cs5',
    name: 'Chicken Matki',
    description: 'Chicken in tomato-onion masala.',
    category: 'chefs_specials',
    price_medium: null,
    price_large: null,
    price_per_piece: null,
    medium_label: 'Medium Tray',
    large_label: 'Large Tray',
    image_url: SUPABASE + 'Chicken%20Matki.png',
    is_available: true,
    sort_order: 29,
  },
  {
    id: 'mnv6',
    name: 'Chicken Methi Malai',
    description: 'Chicken in creamy fenugreek-flecked gravy.',
    category: 'main_course_non_veg',
    price_medium: null,
    price_large: null,
    price_per_piece: null,
    medium_label: 'Medium Tray',
    large_label: 'Large Tray',
    image_url: SUPABASE + 'Chicken%20Methi%20Malai.png',
    is_available: true,
    sort_order: 30,
  },
  {
    id: 'cs6',
    name: 'Chicken Puff Patties',
    description:
      'Flaky pastry stuffed with spiced chicken. Sold per piece.',
    category: 'chefs_specials',
    price_medium: null,
    price_large: null,
    price_per_piece: 5,
    medium_label: null,
    large_label: null,
    image_url: SUPABASE + 'Chicken%20Puff%20Patties%20.png',
    is_available: true,
    sort_order: 31,
  },
  {
    id: 'mnv11',
    name: 'Chicken Qeema Mattar',
    description: 'Minced chicken with peas.',
    category: 'main_course_non_veg',
    price_medium: null,
    price_large: null,
    price_per_piece: null,
    medium_label: 'Medium Tray',
    large_label: 'Large Tray',
    image_url: SUPABASE + 'Chicken%20Qeema%20Matar.png',
    is_available: true,
    sort_order: 32,
  },
  {
    id: 'mnv8',
    name: 'Chicken Saag Wala',
    description: 'Chicken in classic spinach gravy.',
    category: 'main_course_non_veg',
    price_medium: 120,
    price_large: 180,
    price_per_piece: null,
    medium_label: 'Medium Tray',
    large_label: 'Large Tray',
    image_url: SUPABASE + 'Chicken%20Saag%20Wala.png',
    is_available: true,
    sort_order: 33,
  },
  {
    id: 'anv1',
    name: 'Chicken Salami Cold',
    description: 'Chilled chicken salami slices, perfect starter platter.',
    category: 'appetizers_non_veg',
    price_medium: 120,
    price_large: 210,
    price_per_piece: null,
    medium_label: 'Medium Tray',
    large_label: 'Large Tray',
    image_url: SUPABASE + 'Chicken%20Salami.png',
    is_available: true,
    sort_order: 34,
  },
  {
    id: 'anv5',
    name: 'Chicken Tandoori (WB)',
    description: 'Whole-bird West Bengal-style tandoori chicken.',
    category: 'appetizers_non_veg',
    price_medium: 120,
    price_large: 210,
    price_per_piece: null,
    medium_label: 'Medium Tray',
    large_label: 'Large Tray',
    image_url: SUPABASE + 'Tandoori%20Chicken.png',
    is_available: true,
    sort_order: 35,
  },
  {
    id: 'tt8',
    name: 'Chicken Tandoori (WB)',
    description: 'West Bengal-style tandoori chicken.',
    category: 'tandoori_treasures',
    price_medium: 120,
    price_large: 210,
    price_per_piece: null,
    medium_label: 'Medium Tray',
    large_label: 'Large Tray',
    image_url: SUPABASE + 'Tandoori%20Chicken.png',
    is_available: true,
    sort_order: 36,
  },
  {
    id: 'anv2',
    name: 'Chicken Tikka',
    description: 'Yogurt-marinated chargrilled chicken skewers.',
    category: 'appetizers_non_veg',
    price_medium: 110,
    price_large: 190,
    price_per_piece: null,
    medium_label: 'Medium Tray',
    large_label: 'Large Tray',
    image_url: SUPABASE + 'Chicken%20Tikka.png',
    is_available: true,
    sort_order: 37,
  },
  {
    id: 'tt4',
    name: 'Chicken Tikka',
    description: 'Yogurt-marinated chargrilled chicken skewers.',
    category: 'tandoori_treasures',
    price_medium: 110,
    price_large: 190,
    price_per_piece: null,
    medium_label: 'Medium Tray',
    large_label: 'Large Tray',
    image_url: SUPABASE + 'Chicken%20Tikka.png',
    is_available: true,
    sort_order: 38,
  },
  {
    id: 'mnv5',
    name: 'Chicken Tikka Masala',
    description: 'Chargrilled chicken in spiced tomato-cream sauce.',
    category: 'main_course_non_veg',
    price_medium: 120,
    price_large: 180,
    price_per_piece: null,
    medium_label: 'Medium Tray',
    large_label: 'Large Tray',
    image_url: SUPABASE + 'Chicken%20Tikka%20Masala.png',
    is_available: true,
    sort_order: 39,
  },
  {
    id: 'ic13',
    name: 'Chilli Chicken (Dry/Gravy)',
    description:
      'Battered chicken in spicy Indo-Chinese chilli sauce.',
    category: 'indo_chinese',
    price_medium: 90,
    price_large: 140,
    price_per_piece: null,
    medium_label: 'Medium Tray',
    large_label: 'Large Tray',
    image_url: SUPABASE + 'Chilli%20Chicken.png',
    is_available: true,
    sort_order: 40,
  },
  {
    id: 'ic14',
    name: 'Chilli Paneer (Dry/Gravy)',
    description: 'Crispy paneer in spicy chilli sauce.',
    category: 'indo_chinese',
    price_medium: 65,
    price_large: 85,
    price_per_piece: null,
    medium_label: 'Medium Tray',
    large_label: 'Large Tray',
    image_url: SUPABASE + 'Chilli%20Paneer.png',
    is_available: true,
    sort_order: 41,
  },
  {
    id: 'sa2',
    name: 'Chop Green Salad',
    description: 'Finely chopped mixed greens with house vinaigrette.',
    category: 'salad',
    price_medium: 50,
    price_large: 70,
    price_per_piece: null,
    medium_label: 'Medium Tray',
    large_label: 'Large Tray',
    image_url: SUPABASE + 'Chop%20Green%20Salad.png',
    is_available: true,
    sort_order: 42,
  },
  {
    id: 'mv24',
    name: 'Choley',
    description: 'Spiced chickpeas Punjab-style.',
    category: 'main_course_veg',
    price_medium: null,
    price_large: null,
    price_per_piece: null,
    medium_label: 'Medium Tray',
    large_label: 'Large Tray',
    image_url: SUPABASE + 'Choley.png',
    is_available: true,
    sort_order: 43,
  },
  {
    id: 'mv1',
    name: 'Dal Makhani',
    description:
      'Black lentils slow-simmered overnight with cream and butter.',
    category: 'main_course_veg',
    price_medium: 105,
    price_large: 160,
    price_per_piece: null,
    medium_label: 'Medium Tray',
    large_label: 'Large Tray',
    image_url: SUPABASE + 'Daal%20Makhani.jpg',
    is_available: true,
    sort_order: 44,
  },
  {
    id: 'mnv1',
    name: 'Egg Bhurji',
    description: 'Indian-style scrambled eggs with spices.',
    category: 'main_course_non_veg',
    price_medium: null,
    price_large: null,
    price_per_piece: null,
    medium_label: 'Medium Tray',
    large_label: 'Large Tray',
    image_url: SUPABASE + 'Egg%20Burji.jpg',
    is_available: true,
    sort_order: 45,
  },
  {
    id: 'bf2',
    name: 'Egg Biryani',
    description: 'Boiled egg layered biryani.',
    category: 'biryani_flavors',
    price_medium: null,
    price_large: null,
    price_per_piece: null,
    medium_label: 'Medium Tray',
    large_label: 'Large Tray',
    image_url: SUPABASE + 'Egg%20Biryani.png',
    is_available: true,
    sort_order: 46,
  },
  {
    id: 'ic6',
    name: 'Egg Chow Mein',
    description: 'Stir-fried noodles with egg.',
    category: 'indo_chinese',
    price_medium: null,
    price_large: null,
    price_per_piece: null,
    medium_label: 'Medium Tray',
    large_label: 'Large Tray',
    image_url: SUPABASE + 'Egg%20Chowmein.png',
    is_available: true,
    sort_order: 47,
  },
  {
    id: 'mnv3',
    name: 'Egg Curry',
    description: 'Eggs simmered in classic curry sauce.',
    category: 'main_course_non_veg',
    price_medium: null,
    price_large: null,
    price_per_piece: null,
    medium_label: 'Medium Tray',
    large_label: 'Large Tray',
    image_url: SUPABASE + 'Egg%20Curry.jpg',
    is_available: true,
    sort_order: 48,
  },
  {
    id: 'ic2',
    name: 'Egg Fried Rice',
    description: 'Fried rice with scrambled egg.',
    category: 'indo_chinese',
    price_medium: null,
    price_large: null,
    price_per_piece: null,
    medium_label: 'Medium Tray',
    large_label: 'Large Tray',
    image_url: SUPABASE + 'Egg%20Fried%20Rice.png',
    is_available: true,
    sort_order: 49,
  },
  {
    id: 'mnv2',
    name: 'Egg Masala',
    description: 'Hard-boiled eggs in spiced onion-tomato gravy.',
    category: 'main_course_non_veg',
    price_medium: null,
    price_large: null,
    price_per_piece: null,
    medium_label: 'Medium Tray',
    large_label: 'Large Tray',
    image_url: SUPABASE + 'Egg%20Masala.png',
    is_available: true,
    sort_order: 50,
  },
  {
    id: 'mv25',
    name: 'Gatte ki Sabji',
    description: 'Gram-flour dumplings in spiced yogurt curry.',
    category: 'main_course_veg',
    price_medium: null,
    price_large: null,
    price_per_piece: null,
    medium_label: 'Medium Tray',
    large_label: 'Large Tray',
    image_url: SUPABASE + 'Gatte%20ki%20Sabzi.png',
    is_available: true,
    sort_order: 51,
  },
  {
    id: 'mnv16',
    name: 'Goat Beli Raam',
    description: 'Cashew-rich goat curry.',
    category: 'main_course_non_veg',
    price_medium: null,
    price_large: null,
    price_per_piece: null,
    medium_label: 'Medium Tray',
    large_label: 'Large Tray',
    image_url: SUPABASE + 'Goat%20Beli%20Raam.png',
    is_available: true,
    sort_order: 52,
  },
  {
    id: 'bf5',
    name: 'Goat Biryani',
    description: 'Tender goat layered biryani.',
    category: 'biryani_flavors',
    price_medium: null,
    price_large: null,
    price_per_piece: null,
    medium_label: 'Medium Tray',
    large_label: 'Large Tray',
    image_url: SUPABASE + 'Goat%20Biryani.png',
    is_available: true,
    sort_order: 53,
  },
  {
    id: 'mnv15',
    name: 'Goat Korma',
    description: 'Mild creamy goat curry.',
    category: 'main_course_non_veg',
    price_medium: null,
    price_large: null,
    price_per_piece: null,
    medium_label: 'Medium Tray',
    large_label: 'Large Tray',
    image_url: SUPABASE + 'Goat%20Korma.png',
    is_available: true,
    sort_order: 54,
  },
  {
    id: 'mnv14',
    name: 'Goat / Lamb Curry / Goat Curry',
    description: 'Slow-cooked goat in aromatic red curry.',
    category: 'main_course_non_veg',
    price_medium: 150,
    price_large: 250,
    price_per_piece: null,
    medium_label: 'Medium Tray',
    large_label: 'Large Tray',
    image_url: SUPABASE + 'Goat%20or%20Lamb%20Curry.png',
    is_available: true,
    sort_order: 55,
  },
  {
    id: 'sa1',
    name: 'Green Salad',
    description: 'Cucumber, tomato, onion, lemon.',
    category: 'salad',
    price_medium: 50,
    price_large: 70,
    price_per_piece: null,
    medium_label: 'Medium Tray',
    large_label: 'Large Tray',
    image_url: SUPABASE + 'Salad.png',
    is_available: true,
    sort_order: 56,
  },
  {
    id: 'mnv13',
    name: 'Hari Mirch Chicken',
    description: 'Spicy green-chili chicken.',
    category: 'main_course_non_veg',
    price_medium: 120,
    price_large: 180,
    price_per_piece: null,
    medium_label: 'Medium Tray',
    large_label: 'Large Tray',
    image_url: SUPABASE + 'hari%20mirch%20chicken.png',
    is_available: true,
    sort_order: 57,
  },
  {
    id: 'mv6',
    name: 'Jeera Aloo / Jeera Aaloo',
    description: 'Cumin-tempered potatoes, dry and crisp.',
    category: 'main_course_veg',
    price_medium: 105,
    price_large: 160,
    price_per_piece: null,
    medium_label: 'Medium Tray',
    large_label: 'Large Tray',
    image_url: SUPABASE + 'Jeera%20Alu.png',
    is_available: true,
    sort_order: 58,
  },
  {
    id: 'ri2',
    name: 'Jeera Rice',
    description: 'Basmati rice tempered with cumin.',
    category: 'rice',
    price_medium: 50,
    price_large: 70,
    price_per_piece: null,
    medium_label: 'Medium Tray',
    large_label: 'Large Tray',
    image_url: SUPABASE + 'Jeera%20Rice.png',
    is_available: true,
    sort_order: 59,
  },
  {
    id: 'mv11',
    name: 'Kadhai Paneer',
    description: 'Paneer and peppers in smoky kadhai masala.',
    category: 'main_course_veg',
    price_medium: 110,
    price_large: 170,
    price_per_piece: null,
    medium_label: 'Medium Tray',
    large_label: 'Large Tray',
    image_url: SUPABASE + 'Kadhai%20Paneer.png',
    is_available: true,
    sort_order: 60,
  },
  {
    id: 'anv3',
    name: 'Lehsuni Tikka',
    description: 'Garlic-loaded juicy chicken tikka.',
    category: 'appetizers_non_veg',
    price_medium: 110,
    price_large: 190,
    price_per_piece: null,
    medium_label: 'Medium Tray',
    large_label: 'Large Tray',
    image_url:
      'https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=800',
    is_available: true,
    sort_order: 61,
  },
  {
    id: 'tt7',
    name: 'Lehsuni Tikka',
    description: 'Garlic-loaded juicy chicken tikka.',
    category: 'tandoori_treasures',
    price_medium: 110,
    price_large: 190,
    price_per_piece: null,
    medium_label: 'Medium Tray',
    large_label: 'Large Tray',
    image_url:
      'https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=800',
    is_available: true,
    sort_order: 62,
  },
  {
    id: 'mv17',
    name: 'Malai Soya Chaap',
    description: 'Creamy malai-marinated soya chaap pieces.',
    category: 'main_course_veg',
    price_medium: 130,
    price_large: 210,
    price_per_piece: null,
    medium_label: 'Medium Tray',
    large_label: 'Large Tray',
    image_url: SUPABASE + 'Malai%20Soya%20Chaap.png',
    is_available: true,
    sort_order: 63,
  },
  {
    id: 'ri3',
    name: 'Mattar Pulao',
    description: 'Pea pulao.',
    category: 'rice',
    price_medium: null,
    price_large: null,
    price_per_piece: null,
    medium_label: 'Medium Tray',
    large_label: 'Large Tray',
    image_url: SUPABASE + 'Matar%20Pulao.png',
    is_available: true,
    sort_order: 64,
  },
  {
    id: 'ri6',
    name: 'Matar Rice',
    description: 'Basmati with peas.',
    category: 'rice',
    price_medium: 50,
    price_large: 70,
    price_per_piece: null,
    medium_label: 'Medium Tray',
    large_label: 'Large Tray',
    image_url:
      'https://images.unsplash.com/photo-1596560548464-f010549b84d7?w=800',
    is_available: true,
    sort_order: 65,
  },
  {
    id: 'mv21',
    name: 'Mattar Methi Malai',
    description: 'Peas with fenugreek in creamy gravy.',
    category: 'main_course_veg',
    price_medium: null,
    price_large: null,
    price_per_piece: null,
    medium_label: 'Medium Tray',
    large_label: 'Large Tray',
    image_url: SUPABASE + 'Methi%20Malai%20Matar.png',
    is_available: true,
    sort_order: 66,
  },
  {
    id: 'mv16',
    name: 'Mushroom Mattar / Mattar Mushroom',
    description: 'Mushrooms and peas in creamy gravy.',
    category: 'main_course_veg',
    price_medium: 105,
    price_large: 160,
    price_per_piece: null,
    medium_label: 'Medium Tray',
    large_label: 'Large Tray',
    image_url: SUPABASE + 'Mushroom%20Matar.png',
    is_available: true,
    sort_order: 67,
  },
  {
    id: 'tt2',
    name: 'Mushroom Tikka',
    description: 'Chargrilled mushroom skewers.',
    category: 'tandoori_treasures',
    price_medium: null,
    price_large: null,
    price_per_piece: null,
    medium_label: 'Medium Tray',
    large_label: 'Large Tray',
    image_url: SUPABASE + 'Mushroom%20Tikka.png',
    is_available: true,
    sort_order: 68,
  },
  {
    id: 'it3',
    name: 'Mushroom White Sauce Pasta',
    description: 'White-sauce pasta with mushrooms.',
    category: 'italian',
    price_medium: 55,
    price_large: 75,
    price_per_piece: null,
    medium_label: 'Medium Tray',
    large_label: 'Large Tray',
    image_url: SUPABASE + 'Mushroom%20White%20Sauce%20Pasta%20.png',
    is_available: true,
    sort_order: 69,
  },
  {
    id: 'mv13',
    name: 'Mutter Paneer / Mattar Paneer',
    description: 'Paneer and peas in tomato-cashew gravy.',
    category: 'main_course_veg',
    price_medium: 110,
    price_large: 170,
    price_per_piece: null,
    medium_label: 'Medium Tray',
    large_label: 'Large Tray',
    image_url: SUPABASE + 'Matar%20Paneer.png',
    is_available: true,
    sort_order: 70,
  },
  {
    id: 'mv9',
    name: 'Palak Paneer',
    description: 'Paneer cubes in silky spinach gravy.',
    category: 'main_course_veg',
    price_medium: 110,
    price_large: 170,
    price_per_piece: null,
    medium_label: 'Medium Tray',
    large_label: 'Large Tray',
    image_url: SUPABASE + 'Palak%20Paneer.png',
    is_available: true,
    sort_order: 71,
  },
  {
    id: 'mv15',
    name: 'Paneer Bhurji',
    description: 'Crumbled paneer sautéed with peppers and spices.',
    category: 'main_course_veg',
    price_medium: null,
    price_large: null,
    price_per_piece: null,
    medium_label: 'Medium Tray',
    large_label: 'Large Tray',
    image_url: SUPABASE + 'Paneer%20Burji%20.png',
    is_available: true,
    sort_order: 72,
  },
  {
    id: 'mv14',
    name: 'Paneer Butter Masala',
    description: 'Paneer in velvety butter-tomato gravy.',
    category: 'main_course_veg',
    price_medium: 110,
    price_large: 170,
    price_per_piece: null,
    medium_label: 'Medium Tray',
    large_label: 'Large Tray',
    image_url: SUPABASE + 'Paneer%20Butter%20Masala%20.jpg',
    is_available: true,
    sort_order: 73,
  },
  {
    id: 'mv12',
    name: 'Paneer Korma',
    description: 'Mild creamy paneer curry with nuts.',
    category: 'main_course_veg',
    price_medium: 110,
    price_large: 170,
    price_per_piece: null,
    medium_label: 'Medium Tray',
    large_label: 'Large Tray',
    image_url: SUPABASE + 'Paneer%20Korma.png',
    is_available: true,
    sort_order: 74,
  },
  {
    id: 'av5',
    name: 'Paneer Puff Patties',
    description:
      'Flaky pastry stuffed with spiced paneer. Sold per piece.',
    category: 'appetizers_veg',
    price_medium: null,
    price_large: null,
    price_per_piece: 4,
    medium_label: null,
    large_label: null,
    image_url: SUPABASE + 'Paneer%20Puff%20Patties%20.png',
    is_available: true,
    sort_order: 75,
  },
  {
    id: 'tt1',
    name: 'Paneer Tikka',
    description: 'Chargrilled paneer skewers.',
    category: 'tandoori_treasures',
    price_medium: null,
    price_large: null,
    price_per_piece: null,
    medium_label: 'Medium Tray',
    large_label: 'Large Tray',
    image_url: SUPABASE + 'Paneer%20Tikka.png',
    is_available: true,
    sort_order: 76,
  },
  {
    id: 'cs3',
    name: 'Pao Bhaji',
    description: 'Spiced mashed vegs with butter-toasted buns.',
    category: 'chefs_specials',
    price_medium: null,
    price_large: null,
    price_per_piece: null,
    medium_label: 'Medium Tray',
    large_label: 'Large Tray',
    image_url: SUPABASE + 'Pao%20Bhaji.png',
    is_available: true,
    sort_order: 77,
  },
  {
    id: 'mv5',
    name: 'Pindi Chana',
    description: 'Smoky dry-style chickpeas from Punjab.',
    category: 'main_course_veg',
    price_medium: 105,
    price_large: 160,
    price_per_piece: null,
    medium_label: 'Medium Tray',
    large_label: 'Large Tray',
    image_url: SUPABASE + 'Pindi%20Chana%20.png',
    is_available: true,
    sort_order: 78,
  },
  {
    id: 'tt3',
    name: 'Pineapple Tikka',
    description: 'Chargrilled pineapple wedges.',
    category: 'tandoori_treasures',
    price_medium: null,
    price_large: null,
    price_per_piece: null,
    medium_label: 'Medium Tray',
    large_label: 'Large Tray',
    image_url: SUPABASE + 'Pineapple%20Tikka.png',
    is_available: true,
    sort_order: 79,
  },
  {
    id: 'ri1',
    name: 'Plain Rice / White Rice',
    description: 'Steamed long-grain basmati.',
    category: 'rice',
    price_medium: 50,
    price_large: 70,
    price_per_piece: null,
    medium_label: 'Medium Tray',
    large_label: 'Large Tray',
    image_url: SUPABASE + 'Plain%20Rice.png',
    is_available: true,
    sort_order: 80,
  },
  {
    id: 'cs1',
    name: 'Poori',
    description: 'Fluffy deep-fried whole-wheat bread.',
    category: 'chefs_specials',
    price_medium: null,
    price_large: null,
    price_per_piece: null,
    medium_label: 'Medium Tray',
    large_label: 'Large Tray',
    image_url: SUPABASE + 'Poori.png',
    is_available: true,
    sort_order: 81,
  },
  {
    id: 'bf3',
    name: 'Qeema Biryani',
    description: 'Minced-meat biryani.',
    category: 'biryani_flavors',
    price_medium: null,
    price_large: null,
    price_per_piece: null,
    medium_label: 'Medium Tray',
    large_label: 'Large Tray',
    image_url: SUPABASE + 'Qeema%20Biryani.png',
    is_available: true,
    sort_order: 82,
  },
  {
    id: 'cs7',
    name: 'Qeema Puff Patties',
    description:
      'Flaky pastry stuffed with minced meat. Sold per piece.',
    category: 'chefs_specials',
    price_medium: null,
    price_large: null,
    price_per_piece: 5,
    medium_label: null,
    large_label: null,
    image_url: SUPABASE + 'Qeema%20Puff%20Patties.png',
    is_available: true,
    sort_order: 83,
  },
  {
    id: 'mv3',
    name: 'Rajma Curry / Rajma Masala',
    description: 'Kidney beans in thick tomato-onion gravy.',
    category: 'main_course_veg',
    price_medium: 105,
    price_large: 160,
    price_per_piece: null,
    medium_label: 'Medium Tray',
    large_label: 'Large Tray',
    image_url: SUPABASE + 'Rajma%20Curry.jpg',
    is_available: true,
    sort_order: 84,
  },
  {
    id: 'it7',
    name: 'Red Sauce Pasta',
    description: 'Penne in tangy tomato sauce.',
    category: 'italian',
    price_medium: 50,
    price_large: 70,
    price_per_piece: null,
    medium_label: 'Medium Tray',
    large_label: 'Large Tray',
    image_url: SUPABASE + 'Red%20Sauce%20Pasta%20.png',
    is_available: true,
    sort_order: 85,
  },
  {
    id: 'av2',
    name: 'Samosa Cholley',
    description: 'Crispy samosas with spiced choley.',
    category: 'appetizers_veg',
    price_medium: 75,
    price_large: 130,
    price_per_piece: null,
    medium_label: 'Medium Tray',
    large_label: 'Large Tray',
    image_url: SUPABASE + 'Samosa%20Choley.png',
    is_available: true,
    sort_order: 86,
  },
  {
    id: 'mv10',
    name: 'Shahi Paneer',
    description: 'Rich royal-style paneer in creamy cashew-tomato gravy.',
    category: 'main_course_veg',
    price_medium: 110,
    price_large: 170,
    price_per_piece: null,
    medium_label: 'Medium Tray',
    large_label: 'Large Tray',
    image_url: SUPABASE + 'Shahi%20Paneer.png',
    is_available: true,
    sort_order: 87,
  },
  {
    id: 'ic4',
    name: 'Shrimp Fried Rice',
    description: 'Wok-tossed rice with shrimp.',
    category: 'indo_chinese',
    price_medium: 80,
    price_large: 120,
    price_per_piece: null,
    medium_label: 'Medium Tray',
    large_label: 'Large Tray',
    image_url:
      'https://images.unsplash.com/photo-1606491956689-2ea866880c84?w=800',
    is_available: true,
    sort_order: 88,
  },
  {
    id: 'ic10',
    name: 'Shrimp Hakka Noodles',
    description: 'Hakka noodles with shrimp.',
    category: 'indo_chinese',
    price_medium: 80,
    price_large: 120,
    price_per_piece: null,
    medium_label: 'Medium Tray',
    large_label: 'Large Tray',
    image_url: SUPABASE + 'Shrimp%20Hakka%20Noodles.png',
    is_available: true,
    sort_order: 89,
  },
  {
    id: 'tt5',
    name: 'Tandoori Chicken Tikka',
    description: 'Classic tandoori-style chicken tikka.',
    category: 'tandoori_treasures',
    price_medium: null,
    price_large: null,
    price_per_piece: null,
    medium_label: 'Medium Tray',
    large_label: 'Large Tray',
    image_url: SUPABASE + 'Tandoori%20Chicken%20Tikka.png',
    is_available: true,
    sort_order: 90,
  },
  {
    id: 'av1',
    name: 'Tikki Cholley',
    description: 'Crispy potato tikki served with choley.',
    category: 'appetizers_veg',
    price_medium: 75,
    price_large: 130,
    price_per_piece: null,
    medium_label: 'Medium Tray',
    large_label: 'Large Tray',
    image_url: SUPABASE + 'Tikki%20Choley.png',
    is_available: true,
    sort_order: 91,
  },
  {
    id: 'av6',
    name: 'Vada Pav',
    description:
      'Mumbai street-style spicy potato fritter in a soft pav roll with green chutney, fried chili, and garlic chutney.',
    category: 'appetizers_veg',
    price_medium: 75,
    price_large: 130,
    price_per_piece: null,
    medium_label: 'Medium Tray',
    large_label: 'Large Tray',
    image_url: SUPABASE + 'Vada%20Pav.JPG',
    is_available: true,
    sort_order: 92,
  },
  {
    id: 'bf1',
    name: 'Veg Biryani',
    description: 'Layered basmati with veggies and saffron.',
    category: 'biryani_flavors',
    price_medium: null,
    price_large: null,
    price_per_piece: null,
    medium_label: 'Medium Tray',
    large_label: 'Large Tray',
    image_url: SUPABASE + 'Veg%20Biryani.png',
    is_available: true,
    sort_order: 93,
  },
  {
    id: 'ic5',
    name: 'Veg Chow Mein',
    description: 'Stir-fried noodles with veggies.',
    category: 'indo_chinese',
    price_medium: 55,
    price_large: 75,
    price_per_piece: null,
    medium_label: 'Medium Tray',
    large_label: 'Large Tray',
    image_url: SUPABASE + 'Veg%20Chowmein.png',
    is_available: true,
    sort_order: 94,
  },
  {
    id: 'ic1',
    name: 'Veg Fried Rice',
    description: 'Wok-tossed rice with veggies and soy.',
    category: 'indo_chinese',
    price_medium: 55,
    price_large: 75,
    price_per_piece: null,
    medium_label: 'Medium Tray',
    large_label: 'Large Tray',
    image_url: SUPABASE + 'Veg%20Fried%20Rice.png',
    is_available: true,
    sort_order: 95,
  },
  {
    id: 'ic8',
    name: 'Veg Hakka Noodles',
    description: 'Wok-tossed hakka noodles with veggies.',
    category: 'indo_chinese',
    price_medium: 60,
    price_large: 80,
    price_per_piece: null,
    medium_label: 'Medium Tray',
    large_label: 'Large Tray',
    image_url: SUPABASE + 'Veg%20Hakka%20Noodles.png',
    is_available: true,
    sort_order: 96,
  },
  {
    id: 'ic11',
    name: 'Veg Manchurian (Dry/Gravy)',
    description: 'Veggie balls in soy-ginger sauce.',
    category: 'indo_chinese',
    price_medium: 65,
    price_large: 95,
    price_per_piece: null,
    medium_label: 'Medium Tray',
    large_label: 'Large Tray',
    image_url: SUPABASE + 'Veg%20Manchurian.png',
    is_available: true,
    sort_order: 97,
  },
  {
    id: 'ri4',
    name: 'Veg Pulao',
    description: 'Mixed-veggie basmati pulao.',
    category: 'rice',
    price_medium: null,
    price_large: null,
    price_per_piece: null,
    medium_label: 'Medium Tray',
    large_label: 'Large Tray',
    image_url: SUPABASE + 'Veg%20Pulao.png',
    is_available: true,
    sort_order: 98,
  },
  {
    id: 'mv19',
    name: 'Veg Qeema Mattar',
    description: 'Soya qeema with peas.',
    category: 'main_course_veg',
    price_medium: null,
    price_large: null,
    price_per_piece: null,
    medium_label: 'Medium Tray',
    large_label: 'Large Tray',
    image_url: SUPABASE + 'Veg%20keema%20matart.jpg',
    is_available: true,
    sort_order: 99,
  },
  {
    id: 'it1',
    name: 'White Sauce Pasta',
    description: 'Penne in creamy white sauce.',
    category: 'italian',
    price_medium: 50,
    price_large: 70,
    price_per_piece: null,
    medium_label: 'Medium Tray',
    large_label: 'Large Tray',
    image_url: SUPABASE + 'White%20Sauce%20Pasta%20.png',
    is_available: true,
    sort_order: 100,
  },
  {
    id: 'mv2',
    name: 'Yellow Dal Tadka',
    description: 'Yellow lentils tempered with ghee, cumin and garlic.',
    category: 'main_course_veg',
    price_medium: 105,
    price_large: 160,
    price_per_piece: null,
    medium_label: 'Medium Tray',
    large_label: 'Large Tray',
    image_url: SUPABASE + 'Yellow%20Dal%20Tadka%20.jpg',
    is_available: true,
    sort_order: 101,
  },
  {
    id: 'ri5',
    name: 'Yellow Rice',
    description: 'Saffron-tinted basmati.',
    category: 'rice',
    price_medium: 50,
    price_large: 70,
    price_per_piece: null,
    medium_label: 'Medium Tray',
    large_label: 'Large Tray',
    image_url: SUPABASE + 'Yellow%20Rice.png',
    is_available: true,
    sort_order: 102,
  },
];
